[package]
name = "nit"
version = "0.1.4"
edition = "2024"
license = "GPL-3.0-only"
description = "A more secure and reliable alternative to pre-commit."
homepage = "https://github.com/Timmmm/nit/"
repository = "https://github.com/Timmmm/nit/"
documentation = "https://github.com/Timmmm/nit/"

# This gets it down to around 10MB instead of 18MB.
[profile.release-small]
inherits = "release"
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
async-trait = "0.1.91" # Must match the version used by wasmtime-wasi.
anyhow = { version = "1.0.104", features = ["backtrace"] }
blake3 = "1.8.5"
bytes = "1.12.1" # Must match the version used by wasmtime-wasi.
clap = { version = "4.6.4", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["display"] }
dirs = "6.0.0"
env_logger = "0.11.11"
futures = "0.3.33"
gix = "0.86.0"
glob = "0.3.4"
indicatif = { version = "0.18.6", features = ["tokio"] }
itertools = "0.15.0"
log = "0.4.33"
memchr = "2.8.3"
owo-colors = { version = "4.3.0", features = ["supports-color"] }
regex = "1.13.1"
reqwest = { version = "0.13.4", features = ["stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_json5 = "0.2.1"
tokio = { version = "1.53.1", features = ["rt", "macros", "fs"] }
tokio-util = { version = "0.7.19", features = ["io",] }
walkdir = "2.5.0"
wasmtime = "47.0.2"
wasmtime-wasi = "47.0.2"
wasmtime-wasi-io = "47.0.2"
slab = "0.4.12"

# OpenSSL is only used on Unix. We don't want to add it as a dependency on Windows.
[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.70", features = ["vendored"] }

[workspace]
resolver = "2"
members = [
    "lints/lint_case_conflict",
    "lints/lint_deny",
    "lints/lint_executable_shebang",
    "lints/lint_json_format",
    "lints/lint_merge_conflicts",
    "lints/lint_regex",
    "lints/lint_tabs",
    "lints/lint_whitespace",
]

[dev-dependencies]
tempfile = "3.27.0"

# Temporary to get the latest version of Wasmtime.
# [patch.crates-io]
# wasmtime = { git = "https://github.com/bytecodealliance/wasmtime" }
# wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime" }
# wasmtime-wasi-io = { git = "https://github.com/bytecodealliance/wasmtime" }
