name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Versions
      run: |
        git version
        cargo version

    - name: Build and test
      run: |
        cargo test --package lint_case_conflict
        cargo test --package lint_deny
        cargo test --package lint_executable_shebang
        cargo test --package lint_json_format
        cargo test --package lint_merge_conflicts
        cargo test --package lint_regex
        cargo test --package lint_tabs
        cargo test --package lint_whitespace

    - name: Build release WASI
      run: |
        rustup target add wasm32-wasip2
        cargo build --release --target wasm32-wasip2 --package lint_case_conflict
        cargo build --release --target wasm32-wasip2 --package lint_deny
        cargo build --release --target wasm32-wasip2 --package lint_executable_shebang
        cargo build --release --target wasm32-wasip2 --package lint_json_format
        cargo build --release --target wasm32-wasip2 --package lint_merge_conflicts
        cargo build --release --target wasm32-wasip2 --package lint_regex
        cargo build --release --target wasm32-wasip2 --package lint_tabs
        cargo build --release --target wasm32-wasip2 --package lint_whitespace

    - name: Set metadata
      run: |
        # cargo run -- set-metadata --metadata lints/lint_case_conflict/metadata.json      target/wasm32-wasip2/release/lint_case_conflict.wasm
        cargo run -- set-metadata --metadata lints/lint_deny/metadata.json               target/wasm32-wasip2/release/lint_deny.wasm
        # cargo run -- set-metadata --metadata lints/lint_executable_shebang/metadata.json target/wasm32-wasip2/release/lint_executable_shebang.wasm
        cargo run -- set-metadata --metadata lints/lint_json_format/metadata.json        target/wasm32-wasip2/release/lint_json_format.wasm
        # cargo run -- set-metadata --metadata lints/lint_merge_conflicts/metadata.json    target/wasm32-wasip2/release/lint_merge_conflicts.wasm
        cargo run -- set-metadata --metadata lints/lint_regex/metadata.json              target/wasm32-wasip2/release/lint_regex.wasm
        # cargo run -- set-metadata --metadata lints/lint_tabs/metadata.json               target/wasm32-wasip2/release/lint_tabs.wasm
        cargo run -- set-metadata --metadata lints/lint_whitespace/metadata.json         target/wasm32-wasip2/release/lint_whitespace.wasm
